// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Options struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Transaction          string   `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Options) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Options) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Options) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

func init() {
	proto.RegisterType((*Options)(nil), "data.Options")
}

func init() {
	proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206)
}

var fileDescriptor_555bd8c177793206 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x41, 0x0a, 0xc2, 0x30,
	0x10, 0x45, 0x69, 0x2d, 0x16, 0xa7, 0x22, 0x38, 0xab, 0x2c, 0x4b, 0x57, 0xae, 0xb2, 0xf1, 0x06,
	0xf5, 0x00, 0x16, 0x6f, 0x10, 0x93, 0x80, 0xb3, 0x48, 0x26, 0x24, 0xd1, 0xf3, 0x4b, 0x06, 0x04,
	0x77, 0x33, 0xef, 0xc3, 0xff, 0x0f, 0x8e, 0x96, 0x43, 0xe0, 0xa8, 0x53, 0xe6, 0xca, 0x38, 0x38,
	0x53, 0xcd, 0x42, 0x30, 0xde, 0x53, 0x25, 0x8e, 0x05, 0x4f, 0xd0, 0x93, 0x53, 0xdd, 0xdc, 0x5d,
	0x0e, 0x8f, 0x9e, 0x1c, 0x22, 0x0c, 0xd1, 0x04, 0xaf, 0x7a, 0x21, 0x72, 0xa3, 0x82, 0xf1, 0xe3,
	0x73, 0x21, 0x8e, 0x6a, 0x27, 0xf8, 0xf7, 0xe2, 0x0c, 0x53, 0xcd, 0x26, 0x16, 0x63, 0x5b, 0x9b,
	0x1a, 0x24, 0xfd, 0x47, 0xeb, 0x02, 0x67, 0xcb, 0x41, 0xa7, 0x17, 0x95, 0x37, 0x55, 0xaf, 0xdb,
	0xfe, 0x3a, 0xdd, 0xc4, 0x69, 0x6b, 0x4a, 0x5b, 0xf7, 0xdc, 0x8b, 0xdb, 0xf5, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x35, 0xd3, 0x5b, 0x51, 0xab, 0x00, 0x00, 0x00,
}
